import type { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Using Matine",
  description: "Generated by Rodrigues",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Providers>{children}</Providers>;
}
